# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37cf2320814c7702a87d3b8cfda512e497bfd338f09c70a384fb31f7b2de33d7041247da3cc6ad6a3a5713df3815637cc0e43aedc36d092a73c65c78ebdd55f4

test:
  secret_key_base: 9901e7ae6252c4b607f5f1528564abfa021fffb7c7598f800b7f242fd303a9aee037b690711c23a86071d62c2648dd990d8ff33e7fcc94d0a9be59e43a1ca623

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
